version: '3.3'

services:
  jurisai-app:
    build:
      context: ../JurisAI
      dockerfile: Dockerfile
    container_name: jurisai_app
    ports:
      - "3001:3000"
    volumes:
      - ../JurisAI:/app
    environment:
      - NODE_ENV=dev

  rag-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag_service_nr
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=dev
